version: '3'
services:
  app:
    image: springboot-restful-webservices
    ports:
      - 8080:8080
    networks:
      - springboot-mysql-net
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: order_management
      MYSQL_USER: springuser
      MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - springboot-mysql-net
networks:
  springboot-mysql-net:
volumes:
  db_data:
